### ISSUE TITLE
Unable to generate log due to unproper log file directory

### ISSUE THREAD

**Issue by novahs** [industrial-edge/device-kit-system-service#11]
## Summary

Unable to generate log when the file system is read only.

## Version of the used components

Which versions of the Industrial Edge components did you use?

- IEDK V1.8 (dm-system v1.6)

## Steps to reproduce

With debian squashfs where the rootfs (except for /var /etc , etc) is read-only. 

The service tries to generate logs under /usr/bin, which is read-only and by convention not a correct place to generate runtime files.

Try to download the log from IED UI.

## What is the current bug behavior?

Error. Unable to generate the log file.
![image](https://user-images.githubusercontent.com/119834937/206113340-b2446922-a655-4696-9673-f9d293d21dda.png)

## What is the expected correct behavior?

Should be able to download with no service error.

## Line of code

https://github.com/industrial-edge/device-kit-system-service/blob/main/internal/systeminfo/systeminfo.go#L328

See PR: https://github.com/industrial-edge/device-kit-system-service/pull/10

**Comment by novahs** [comment]
add another PR for improving the tests in : https://github.com/industrial-edge/device-kit-system-service/pull/12

**Comment by kayvaz** [comment]
@novahs Thank you for your contribution. We will investigate the issue.

**Comment by saffetturkoglu** [comment]
Dear @novahs  

Thank you so much for your invaluable contribution and support to our project. We appreciate your effort and time dedicated to resolving the issue by providing the code changes.

We are pleased to inform you that we have included your development in the latest release, version release/1.7.1-3. We're grateful for your collaboration.

Best regards,
